# example:
#   # executes on the hour, every hour
#   cron: * 0 * * * 
#   class: Example
#   queue: example_queue
#   description: It does some things

# class Example
#   @queue = :example_queue
#   def self.perform
#     puts "Hello every hour!"
#   end
# end